In [2]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
result=np.where(arr==6)
print(result)


(array([1, 4]),)


In [4]:
result=np.where(arr==7)
print(result)

(array([3]),)


In [24]:
import numpy as np
arr=np.array([1,6,2,7,6,4])
result=np.where(arr%2==0)
print(result)


(array([1, 2, 4, 5]),)


In [46]:
import numpy as np
arr=np.array([1,2,3,7,8,9])
result=np.searchsorted(arr,8,side='left')
print(result)

4


In [42]:
import numpy as np
arr=np.array([1,2,3,7,8,9])
result=np.searchsorted(arr,8,side='right')
print(result)

5


In [48]:
import numpy as np
arr=np.array([9,5,2,7,6,4])
result=np.sort(arr)
print(result)

[2 4 5 6 7 9]


In [58]:
#Boolean_indexing
import numpy as np
arr=np.array([31,78,69,100])
x=([False,True,False,True])
newarr=arr[x]
print(x)
print(newarr)

[False, True, False, True]
[ 78 100]
