In [1]:
import numpy as op
a=op.array([10,20,30,40])
print("one dimensional array:",a)

one dimensional array: [10 20 30 40]


In [3]:
import numpy as op
b=op.array([[10,20,30,40],[50,60,70,80]])
print("two dimensional array:",b)

two dimensional array: [[10 20 30 40]
 [50 60 70 80]]


In [5]:
import numpy as np
c=np.zeros([3,5])
print("\n array with a zeros \n",c)


 array with a zeros 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
import numpy as np
c=np.random.random([3,5])
print("\n array with random values\n",c)


 array with random values
 [[0.98604067 0.60782062 0.37393906 0.35764481 0.2477078 ]
 [0.50411357 0.94161899 0.00986626 0.84928933 0.96736042]
 [0.89414261 0.55967395 0.19707084 0.72036996 0.059991  ]]


In [15]:
import numpy as np
c=np.arange(0,20,5)
print("\n array with a zeros\n",c)


 array with a zeros
 [ 0  5 10 15]


In [23]:
import numpy  as op
c=op.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarray=c.reshape(4,3)
print("\n three dimensional array:\n",c)
print("\n reshaped array:\n",newarray)


 three dimensional array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [3]:
import numpy  as op
arr=op.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
c=arr.flatten()
print("\n three dimensional array:\n:",arr)
print("\n flatten array:\n",c)


 three dimensional array:
: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 flatten array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [25]:
import numpy  as op
arr=op.array([1,2,3,4])
print("\n three dimensional array:\n:",arr)
print("\n array's dimension:\n",arr.ndim)


 three dimensional array:
: [1 2 3 4]

 array's dimension:
 1


In [23]:
import numpy  as op
arr=op.array([[1,2,3,4],[5,6,7,8]])
print("\n three dimensional array:\n:",arr)
print("\n array's dimension:\n",arr.ndim)


 three dimensional array:
: [[1 2 3 4]
 [5 6 7 8]]

 array's dimension:
 2


In [31]:
import numpy  as op
arr=op.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("\n three dimensional array:\n:",arr)
print("\n array's dimension:\n",arr.ndim)


 three dimensional array:
: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 array's dimension:
 2


In [35]:
import numpy  as op
arr=op.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("\n three dimensional array:\n:",arr)
print(arr.shape)


 three dimensional array:
: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [43]:
import numpy  as op
arr=op.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("\n three dimensional array:\n:",arr)
print("\n array data type:\n:",arr.dtype)


 three dimensional array:
: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 array data type:
: int64


In [49]:
import numpy  as op
arr=op.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("\n three dimensional array:\n:",arr)
print("\n array's length:\n:",len(arr))


 three dimensional array:
: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

 array's length:
: 4


In [3]:
import numpy as np 
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)

[1. 2. 3.]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[2:6]
print(slice)


[3 4 5 6]


In [11]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
slice=arr[::-1]
print(slice)

[9 8 7 6 5 4 3 2 1]


In [31]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
substring=arr[0:3,1:3]
print(substring)

[[2 3]
 [5 6]
 [8 9]]


In [47]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
substring=arr[0:3,1:3]
print("substring:\n",substring)
column1=arr[:,0]
print("columnslicing\n:",column1)

substring:
 [[2 3]
 [5 6]
 [8 9]]
columnslicing
: [1 4 7]


In [49]:
row1=arr[0,:]
print("rowslicing\n:",row1)

rowslicing
: [1 2 3]


In [53]:
import numpy as np
import array
arr=array.array('i',[10,20,30,40,50])
print(arr[0])
print(arr[3])

10
40


In [61]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])

1


In [63]:
print(arr[1:4])

[[4 5 6]
 [7 8 9]]


In [13]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[arr<20])

[1 2 3 4 5 6 7 8 9]


In [7]:
#horizontal_join
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [9]:
#vertical_join
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
#depth_join
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [29]:
#array_splitting_unequal
import numpy as np
arr=np.array([1,2,3,4,5])
result=np.array_split(arr,3)
print (result)

[array([1, 2]), array([3, 4]), array([5])]


In [31]:
#array_splitting_equal
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print (result)

[array([1, 2]), array([3, 4]), array([5, 6])]
