In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
slice1=a[2:10:3]
print(slice1)




[3 6 9]


In [2]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,9,20,21,22])
slice1=a[2::3]
print(slice1)




[ 3  6  9 12 15 18 21]


In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
reva=a[::-1]
print(reva)




[10  9  8  7  6  5  4  3  2  1]


In [12]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
subarray=a[0:2,1:3]
print(subarray)




[[2 3]
 [5 6]]


In [13]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
col1=a[:,0]
print(col1)


[1 4 7]


In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
row1=a[0,:]
print(row1)


[1 2 3]


In [17]:
import numpy as np
import array
a=array.array('i',[1,2,3,4,5])
print(a[0])



1


In [2]:
import numpy as np
import array
a=array.array('i',[1,2,3,4,5])
print(a[0])



1


In [4]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [5]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [9]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])

result=np.split(arr1,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]
