In [5]:
import numpy as np
a=np.array([1,2,3])
print("one dimensional array : \n ",a)

one dimensional array : 
  [1 2 3]


In [4]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("two dimensional array : \n ",a)

two dimensional array :
  [[1 2 3]
 [4 5 6]]


In [6]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("three dimensional array : \n ",a)

three dimensional array : 
  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
import numpy as np
a=np.zeros((3,3))
print("all zeros array : \n ",a)

all zeros array : 
  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
import numpy as np
a=np.random.random((3,3))
print("random value array : \n ",a)

random value array : 
  [[0.74159793 0.26172918 0.39660824]
 [0.13453893 0.64124565 0.3947211 ]
 [0.02739288 0.18326868 0.12526122]]


In [12]:
import numpy as np
a=np.arange(0,10,2)
print("sequence array : \n ",a)

sequence array : 
  [0 2 4 6 8]


In [15]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=a.reshape(3,4)
print("original array : \n ",a)
print("reshaped array : \n ",b)

original array : 
  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
reshaped array : 
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=a.flatten()
print("original array : \n ",a)
print("flattened array : \n ",b)

original array : 
  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
flattened array : 
  [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(" shape of the array :",a.shape)

 shape of the array : (4, 3)


In [28]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("array type :",a.dtype)

array type : int64


In [29]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
size=len(a)
print(" size of the array :",size)

 shape of the array : 4


In [1]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(newtype)
print(newtype.dtype)

[1. 2. 3.]
float64
