In [3]:
import numpy as np
a=np.random.random((3,4))
print("\nArray with random values:\n",a)


Array with random values:
 [[0.99445345 0.87326557 0.27356253 0.97625587]
 [0.52264363 0.78881273 0.58714542 0.94491241]
 [0.8837431  0.47164486 0.7965497  0.59646432]]


In [4]:
import numpy as np
a=np.zeros((3,4))
print("\nArray with zeros:\n",a)


Array with zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
import numpy as np
a=np.arange(5,31,2)
print("\nArray with sequence:\n",a)


Array with sequence:
 [ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [7]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a.flatten()
print("\nShape of array:\na.shape")
print("\nDimension of array:\n",a.ndim)
print("\nDatatype of array:\n",a.dtype)
print("\nFlatten array:\n",b)


Shape of array:
a.shape

Dimension of array:
 2

Datatype of array:
 int64

Flatten array:
 [1 2 3 4 5 6 7 8 9]
